server:
  port: 8081
spring:
  application:
    name: "accounts"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/lidaa/protocol/openid-connect/certs
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DATABASE_NAME:postgres_local}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:lidaa}
    password: ${DB_PASS:admin@123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  config:
    import: "optional:configserver:http://localhost:8071/"


management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: 1.0

springdoc:
  show-actuator: false
  oAuthFlow:
    authorizationUrl: http://localhost:8080/realms/lidaa/protocol/openid-connect/auth
    tokenUrl: http://localhost:8080/realms/lidaa/protocol/openid-connect/token
  swagger-ui:
    display-request-duration: true
    oauth:
      clientId: lidaa
      clientSecret: J50SnElpPHd6xt0ZaWHgipqo19Lvcs7C

jwt-mapping:
  identityProvider: keycloak
  authorityPrefix: ROLE_
  principalClaim: preferred_username

logging:
  level:
    com.lidaa.accounts: INFO
